name: benchmark-exahype-tsunami
on:
  push:
    branches:
      - 'main'
  workflow_dispatch:
jobs:
  build-amd64:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: benchmarks/exahype-tsunami/
          platforms: linux/amd64
          push: true
          tags: linusseelinger/benchmark-exahype-tsunami:latest

  build-arm64:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: benchmarks/exahype-tsunami/
          platforms: linux/arm64
          push: true
          tags: linusseelinger/benchmark-exahype-tsunami-arm:latest

  test-amd64:
    runs-on: ubuntu-latest
    needs: build-amd64
    services:
      model:
        image: linusseelinger/benchmark-exahype-tsunami:latest
        ports:
        - 4243:4243
    steps:
      -
        name: Validate
        run: |
          docker run --network=host -e model_host=http://localhost:4243 linusseelinger/testing-protocol-conformity-current:latest

  test-arm64:
    runs-on: ubuntu-24.04-arm
    needs: build-arm64
    services:
      model:
        image: linusseelinger/benchmark-exahype-tsunami-arm:latest
        ports:
        - 4243:4243
    steps:
      -
        name: Validate
        run: |
          docker run --network=host -e model_host=http://localhost:4243 linusseelinger/testing-protocol-conformity-current:latest
